Add roundtrip test for model files
Deltares/Ribasim pull request #1007
Opened 2024-01-30 11:33 UTC by visr

Fixes #682. It was already fixed, but this ensures it with an extra test.

2024-01-30 13:56 UTC, Hofer-Julian approved these changes
Looks good to me

2024-01-30 13:56 UTC, Hofer-Julian requested changes
Seems like tests are still failing

2024-01-30 13:59 UTC, visr commented
The binary diff on the database is probably too brittle. It would be more convenient to use [sqldiff](https://sqlite.org/sqldiff.html), which gives:

```
❯ sqldiff 1\database.gpkg 2\database.gpkg
UPDATE gpkg_contents SET last_change='2024-01-30T09:47:02.855Z' WHERE rowid=1;
UPDATE gpkg_contents SET last_change='2024-01-30T09:47:02.874Z' WHERE rowid=2;
UPDATE gpkg_contents SET last_change='2024-01-30T09:47:02.891Z' WHERE rowid=3;
UPDATE gpkg_contents SET last_change='2024-01-30T09:47:02.902Z' WHERE rowid=4;
UPDATE gpkg_contents SET last_change='2024-01-30T09:47:02.911Z' WHERE rowid=5;
UPDATE gpkg_contents SET last_change='2024-01-30T09:47:02.926Z' WHERE rowid=6;
UPDATE gpkg_contents SET last_change='2024-01-30T09:47:02.937Z' WHERE rowid=7;
UPDATE gpkg_contents SET last_change='2024-01-30T09:47:02.947Z' WHERE rowid=8;
```

I cannot seem to get that tool from conda-forge though.

I wonder why Python 3.10 and 3.12 are different though, only on Windows.

2024-02-09 16:54 UTC, visr commented on python/ribasim/ribasim/model.py
>          }
I left out the network since it really isn't a node, and is such a different beast that it usually needs to be handled separately from the nodes.

2024-02-09 16:58 UTC, visr commented
This now compares the DataFrames rather than the GeoPackage bytes.

2024-02-09 17:36 UTC, Hofer-Julian approved these changes

2024-02-09 17:36 UTC, merged