Allow no allocation model
Deltares/Ribasim pull request #1134
Opened 2024-02-15 14:36 UTC by visr

Fixes #1133

2024-02-15 14:39 UTC, Hofer-Julian commented on core/src/callback.jl
> +    return if isnothing(idx)
```suggestion
    if isnothing(idx)
```

2024-02-16 09:32 UTC, SouthEndMusic reviewed
I (and @evetion) don't like the way this problem is resolved. I much prefer that in `set_control_params!` the function `set_fractional_flow_in_allocation!` is only called if `config.allocation.use_allocation`.

2024-02-16 10:43 UTC, visr commented
I though about using the `config` at first, but went for this since we don't have the Config available during runtime, it is not part of the Parameters. And the line `if isnothing(idx)` suggested to me that it was meant to work like this in the first place.

The Config is in the Model struct. I feel like generally it is a nice split to not require it during runtime, and I don't know if it would go along well with autodiff. So I feel like your suggestion would need a large refactor that perhaps should be a separate PR?

Or perhaps we could add a field `active::Bool` to `struct Allocation` so this information ends up in the parameters? Or a function `is_active(allocation::Allocation) = isempty(allocation.allocation_models)`? That could be done in this PR. What do you think?

2024-02-16 11:36 UTC, SouthEndMusic commented
Such an inspirational branch name btw ^^

2024-02-16 12:22 UTC, visr commented
You ain't seen `nothing` yet.

2024-02-16 12:33 UTC, SouthEndMusic requested changes
It should be the opposite right? Seems like we don't test this  yet

2024-02-16 12:33 UTC, SouthEndMusic commented on core/src/parameter.jl
> +is_active(allocation::Allocation) = isempty(allocation.allocation_models)
```suggestion
is_active(allocation::Allocation) = !isempty(allocation.allocation_models)
```

2024-02-16 12:39 UTC, visr commented on core/src/parameter.jl
> +is_active(allocation::Allocation) = isempty(allocation.allocation_models)
Ha, my bad.

2024-02-16 12:40 UTC, SouthEndMusic approved these changes

2024-02-16 12:41 UTC, merged