Let solver integrate flows
Deltares/Ribasim pull request #1444
Opened 2024-04-30 15:11 UTC by SouthEndMusic

Fixes https://github.com/Deltares/Ribasim/issues/1431.

To do:
- [x] Let the solver integrate edge flows
- [ ] Let the solver integrate basin forcings
- [ ] Update Jacobian Sparsity tests (and others if needed)

2024-05-01 07:49 UTC, SouthEndMusic commented
There seems to be something broken in adaptive timestepping. It looks like timesteps are allowed to be arbitrarily small (no matter the solver settings), which would explain why running the `backwater` model takes a ridiculous amount of time and this doesn't throw an error:

https://github.com/Deltares/Ribasim/blob/79aa2dfdc3e586c66e38317358dcea02bbe9a73b/core/test/bmi_test.jl#L14-L15

It also looks like that comment is outdated, because you don't give a negative `dt` but I suspect a too small one

2024-05-01 19:37 UTC, visr commented
> It also looks like that comment is outdated

It doesn't look outdated to me. First you update to t=dt0, then to t=dt2/0, which is before the current t. The SciML methods expect a dt argument, whereas BMI expects a t argument.

2024-05-02 06:31 UTC, SouthEndMusic commented on core/src/model.jl
> +
If desired, we could apply different tolerances to different components of the states this way

2024-05-06 16:03 UTC, visr reviewed
Looks good, though the "mean_flow" test perhaps needs some double checking to see if it is ok. A flow of 0.84 where it should be 1 seems quite a large difference, though if it is only for tiny dt and evens out properly over time it should be fine.

2024-05-07 11:06 UTC, SouthEndMusic commented on core/src/solve.jl
> +    forcings_integrated(du) .= vertical_flux
I've added a test

2024-05-07 11:34 UTC, SouthEndMusic commented on core/src/solve.jl
> +    end
Should we build in an error within `inflow_id` etc. to check whether it is requested for a node type for which the neighbors are precalculated?

2024-05-13 13:07 UTC, evetion requested changes
Can't comment on the solver changes/setup, but overall looks ok to me, some small comments.

FWIW I would be useful for others to have a nice PR description (which turns into a commit message after (squash) merging) at least detailing what changed in the internal API for other developers who didn't see these changes.

2024-05-13 13:08 UTC, evetion commented
Also, this seems a net change in terms of lines added/removed, contrary to the original idea in #1431. Do we think this lowered our maintenance? How is the performance affected?

2024-05-13 14:57 UTC, SouthEndMusic commented
So it turns out that this is pretty bad for performance, it basically negates all performance gain from https://github.com/Deltares/Ribasim/pull/1457 as measured iwith the HWS model. So here's a wild idea: What if we set up a parallel ODE problem for the flow integration with an explicit solver?

2024-05-14 11:50 UTC, visr commented
Too bad this didn't work out performance wise, good effort though.

2024-05-14 11:50 UTC, closed without merging