Update install.qmd
Deltares/Ribasim pull request #1642
Opened 2024-07-22 10:54 UTC by Fati-Mon

Adjusted testing if ribasim is succesfully installed.

Fixes #

2024-07-22 11:50 UTC, Jingru923 requested changes

2024-07-22 11:50 UTC, Jingru923 commented on docs/install.qmd
> +executable is in the main folder.
```suggestion
executable is in the main folder.
```

2024-07-22 11:50 UTC, Jingru923 commented on docs/install.qmd
> +To check whether the installation was performed successfully, open 'cmd' go to the path where the executable is for example 'C:\Ribasim9\ribasim_windows' and and type `ribasim` with no arguments in t
```suggestion
To check whether the installation was performed successfully, open a terminal and go to the path where the executable is for example 'C:\Ribasim\ribasim_windows' and and type `ribasim` with no arguments in the command line.
```

2024-07-23 08:42 UTC, visr commented on docs/install.qmd
> +executable is in the main folder.
```suggestion
executable is in the root folder. 
```

2024-07-23 08:52 UTC, visr approved these changes

2024-07-23 09:52 UTC, merged