Enable migrations from older database schemas.
Deltares/Ribasim pull request #1764
Opened 2024-08-26 16:06 UTC by evetion

Fixes https://github.com/Deltares/Ribasim-NL/issues/138

2024-08-27 08:16 UTC, deltamarnix commented
I would like to opt to add a geopackage version in this PR and let's call everything that doesn't have it version 0, and from now on we will write a `modelversion: 1`. Otherwise we might get conflicts when we figure out that more backwards compatibility is required in the coming months. Then while writing migration, first check if the version is correct.

- [ ] change QGIS writing
- [ ] change Ribasim python writing
- [ ] Write the geopackage version during migration if it was successful? (Maybe not, since it's only in memory migration)
- [ ] Check in your migration code what the version is to migrate

For now, let's keep it as simple as you have it, although I would rather see a pipeline that migrates step by step. But that's for another moment in time.

2024-08-27 12:31 UTC, visr commented
This doesn't yet include removing `listen_node_type` columns:

```
ValidationError: 1 validation error for TableModel[DiscreteControlVariableSchema]
df
  Value error, Unrecognized column 'listen_node_type'.
```

2024-08-28 11:29 UTC, evetion commented
@deltamarnix This now writes the schema version to the geopackage (also from QGIS), which is used to check whether to migrate or not. @visr This now also migrates the other tables with `listen_node_type`.

2024-08-28 14:27 UTC, deltamarnix commented on python/ribasim/ribasim/db_utils.py
> +    return '"' + identifier.replace('"', '""') + '"'
Would something like this be more readable?

```suggestion
    identifier = identifier.replace('"', '""')
    return f'"{identifier}"'
```

2024-08-28 14:42 UTC, deltamarnix requested changes
I want to see tests for the migration and the writing of the version files (both qgis and ribasim python)

2024-08-28 14:42 UTC, deltamarnix commented on python/ribasim/ribasim/db_utils.py
> +    return result
```suggestion
        if not exists(connection, "ribasim_metadata"):
          return 0
        with closing(connection.cursor()) as cursor:
            cursor.execute(
                "SELECT value FROM ribasim_metadata WHERE key='schema_version'"
               )
                return int(cursor.fetchone()[0])
```

2024-08-28 14:42 UTC, deltamarnix commented on python/ribasim/ribasim/migrations.py
> +        df.drop("urban_runoff", inplace=True, axis=1)
Like codecov is saying, tests would be great.

2024-08-28 14:42 UTC, deltamarnix commented on ribasim_qgis/core/geopackage.py
> +def write_schema_version(path: Path, version: int = 1) -> None:
I would also love to see tests for this function.

2024-08-28 14:42 UTC, deltamarnix commented on python/ribasim/ribasim/db_utils.py
> +    return result
It looks like a lot, but it's a simple if-inversion actually.

2024-08-29 12:06 UTC, deltamarnix approved these changes
If @SnippenE agrees that loading an old model in QGIS does not do the migration, but crashes instead, I am okay with the changes so far.

2024-08-29 14:15 UTC, merged