More accurate interpolation and ManningResistance
Deltares/Ribasim pull request #314
Opened 2023-06-14 13:41 UTC by SouthEndMusic

I have implemented the physical interpolation (as proposed in https://github.com/Deltares/Ribasim/issues/225). I have not checked whether this implementation is exactly what we want for extrapolation (https://github.com/Deltares/Ribasim/issues/279), but this implementation assumes that the storage is 0 at the lowest level and does linear extrapolation of the area as a function of the level based on the last 2 values.

This does not solve the problem of high oscillating flows produced by the ManningResistance node as hoped (https://github.com/Deltares/Ribasim/issues/80). I think the problem there is that the calculated flows are way to large, and therefore the equilibrium is overshooted at every time step.

I cannot wrap my head around the current ManningResistance implementation. I understand that flow occurs due to a difference in level, but I do not understand why that means that all the water comes in motion, not just the bit at the top (which is why I find LinearResistance more intuitive). Is anyone familiar with a ManningResistance being used for flow that can go both directions, or is it only used for flow that goes one direction due to gravity? In that last case I understand better why all water is in motion.

Also, the current implementation assumes the presence of a lot of water in the channel itself, which fluctuates with the level in the upstream basin with no regard for (local) water preservation.

2023-06-15 09:35 UTC, SouthEndMusic commented
I restricted this PR to the profile interpolation since fixing the ManningResistance turns out to be a separate problem.

2023-06-16 08:36 UTC, visr requested changes
It looks good to me overall, I left some comments. Let's add some tests for `get_area_and_level`. For that I think you can create a Basin directly (not an entire test model), and then make sure you check all 3 main branches, including the area_diff 0 branches.

2023-06-16 08:36 UTC, visr commented on core/src/utils.jl
> +    # TODO: Is this function still needed now that it is so simple?
Fine by me to replace with `bottom = basin.level[i][1]` in formulate.

2023-06-16 08:36 UTC, visr commented on core/src/utils.jl
> +    # TODO: Is this function still needed now that it is so simple?
It's still about 8 lines of code, making it easier to read: `bottom_a = basin_bottom(basin, basin_a_id)`

2023-06-16 08:36 UTC, visr commented on core/src/utils.jl
> +        if area_diff == 0
```suggestion
        if area_diff ≈ 0
```

I think that's better to allow for floating point inaccuracies.

2023-06-16 08:36 UTC, visr commented on core/src/utils.jl
> +        if area_diff == 0
```suggestion
        if area_diff ≈ 0
```

2023-06-16 08:36 UTC, visr commented on core/src/utils.jl
> +        level_diff = level_higher - level_lower # This should never be 0, validate?
Perhaps it's good to add this comment to https://github.com/Deltares/Ribasim/issues/279

2023-06-19 18:59 UTC, visr approved these changes

2023-06-19 18:59 UTC, merged